export const conePetSayings: string[] = [
  'Banana for scale.',
  'Touch grass\u2026 in Gorilla Tag.',
  'I am the cone.',
  'Boop.',
  'Nice grab.',
  'Where is my forest?',
  "Pro tip: don't fall.",
  'ii Engine go brrr.',
  'That was intentional.',
  'Click me again. I dare you.',
  "I'm not a traffic cone. I'm culture.",
  'Mods loading\u2026 maybe.',
  'Steam says hi.',
  'BepInEx whispered secrets.',
  'Your DLL smells like victory.',
  "Tag you're it.",
  'I saw that lag spike.',
  'Quest battery anxiety.',
  'PCVR supremacy\u2026 or not.',
  'Canyons at sunset hit different.',
  'City map chaos agent.',
  'Forest campfire vibes.',
  "Please don't uninstall me.",
  'I live on your desktop rent-free.',
  'Subtle blink achieved.',
  'Looking left. Looking right. Judging.',
  'Build succeeded. Probably.',
  'Install the menu first.',
  'Health & Repair is your friend.',
  'Backups save friendships.',
  'Pro lounge is cozy.',
  'Experimental and proud.',
  "Don't tell Support I said this.",
  'Discord role go spin.',
  'Orange is a lifestyle.',
  'Warm mode. Still just a cone.',
  'I contain multitudes of squeaks.',
  'Randomness protocol engaged.',
  '404: seriousness not found.',
  'Have you tried turning Gorilla Tag off and on again?',
  'I once met a stump. We nodded.',
  'Your cursor is very brave.',
  'This desktop has good vibes.',
  "I'm legally distinct from a witch hat.",
  'Please clap.',
  'Soft cone noises.',
  'Hard cone noises.',
  'Medium cone noises.',
  "I'm buffering personality.",
  'Achievement unlocked: clicked a cone.',
  'Side quest: feed the cone compliments.',
  'Main quest: ship the build.',
  'Loading witty remark\u2026 done.',
  'I refuse to be ignored.',
  'The window is transparent. I am not.',
  'Always on top of my feelings.',
  'Skip taskbar, never skip snacks.',
  'Frameless and fabulous.',
  'Tauri made me possible.',
  'Rust in peace, bad builds.',
  'Vite fast, cone faster.',
  'Zustand stores my secrets.',
  'I prefer JPEG sunsets.',
  'Blur intensity: emotional.',
  'Sidebar collapsed my patience.',
  'Launch with ii\u2026 and me.',
  'Play without ii? Bold of you.',
  'Verify file integrity of your heart.',
  'Trusted mods only in my friend group.',
  'Community review pending on my jokes.',
  'Experimental features include this sentence.',
  'Giveaways: imaginary bananas.',
  'Unbanned account energy.',
  'Shiny rocks currency when?',
  'I accept pets as tribute.',
  "Blink twice if you're shipping tonight.",
  'Look left for bugs. Look right for features.',
  'Idle animation is my cardio.',
  'Drag responsibly.',
  'Drop me gently.',
  'I do not fetch. I commentate.',
  'Your Pro badge is showing.',
  'Customize me like you mean it.',
  'Preset imported. Personality intact.',
  'Layout wide enough for thoughts.',
  'Focus mode: cone.',
  'Classic cone never dies.',
  'I speak fluent nonsense.',
  'RNG blessed this click.',
  'Seed: orange.',
  'Null pointer, full cone.',
  'Stack overflow of jokes.',
  'Heap of bananas.',
  'Promise resolved: silliness.',
  'Async cone awaits.',
  'Awaiting your next click\u2026',
  'Timeout: still cute.',
  'Retry with exponential joy.',
  "Telemetry says you're cool.",
  'Anonymous chat, loud cone.',
  'Pro lounge would invite me.',
  'Staff tools fear me.',
  'Owner override: more jokes.',
  'Admin approved this message.',
  'Beta access to slapstick.',
  'Stable channel of chaos.',
  'Release candidate: comedy.',
  'Checksum of whimsy verified.',
  'SBOM includes one cone.',
  'License: be nice.',
  'I contain no malware. Only vibes.',
  'True positive: you clicked me.',
  'Confusion matrix: highly confused.',
  "Model hallucination: I'm a dragon.",
  "Actually I'm a cone. Mostly.",
  'Fine-tuned on orange.',
  'Temperature: spicy.',
  'Tokens remaining: infinite giggles.',
  'Context window full of forest.',
  'Nearest neighbor: stump.',
  'Learning rate too high for dignity.',
  'Epoch 9000: still blinking.',
  'Loss function: seriousness.',
  'F1: fun first.',
  'AUC: area under cone.',
  'Overfit to jokes.',
  'Batch size: one click.',
  'Human feedback: click harder.',
  'RLHF: reward laughter.',
  'Policy: be chaotic good.',
  'Exploration: looking around.',
  'Exploitation: more jokes.',
  "Null hypothesis: I'm boring. Rejected.",
  "Alternative: I'm hilarious. Accepted.",
  'Survey says: click again.',
  'TED talk: How to Cone.',
  'Podcast: Soft Cone Noises.',
  'Documentary: Waiting for Click.',
  "Plot twist: I'm helpful sometimes.",
  'Sequel: Cone Pet 2: Electric Boogaloo.',
  'Easter egg: you found me.',
  'Speedrun any%: click click click.',
  'Patch notes: more nonsense.',
  'Feature flag: humor=true.',
  "On-call: I'm always on top.",
  'SLA: silly latency acceptable.',
  'Uptime: emotionally available.',
  'Postmortem: we shipped joy.',
  "Standup: I stood. I'm a cone.",
  'Backlog: infinite jokes.',
  'KPI: giggles per click.',
  'North star: orange glow.',
  'Ship it.',
  'Works on my desktop.',
  'Cannot reproduce seriousness.',
  "Won't fix: being a cone.",
  'By design: chaos.',
  'Priority P0: play.',
  'Severity: adorable.',
  'Legacy: classic cone.',
  'Modern: experimental cone.',
  'Present: your friend.',
  'Fun fact #1: cones are friends.',
  'Day 2: still a cone.',
  'Message #3 from the void.',
  'Whisper #4: ships mods carefully.',
  'Oracle says #5: stay hydrated.',
  'Debug log #6: all orange.',
  'Secret #7: the cone knows.',
  'Tip #8: save before Build & Play.',
  'Note #9: drag me by the head.',
  'Ping #10: still watching.',
  'Chapter 11: the cone blinks.',
  'Episode 12: looking around.',
  'Quirk #13: I say anything.',
  'Rumor #14: Pro pets hit different.',
  'Spark #15: customization forever.',
  'Memo #16: orange forever.',
  'Broadcast #17: boop received.',
  'Signal #18: blink complete.',
  'Fun fact #19: cones are friends.',
  'Day 20: still a cone.',
  'Message #21 from the void.',
  'Whisper #22: ships mods carefully.',
  'Oracle says #23: stay hydrated.',
  'Debug log #24: all orange.',
  'Secret #25: the cone knows.',
  'Tip #26: save before Build & Play.',
  'Note #27: drag me by the head.',
  'Ping #28: still watching.',
  'Chapter 29: the cone blinks.',
  'Episode 30: looking around.',
  'Quirk #31: I say anything.',
  'Rumor #32: Pro pets hit different.',
  'Spark #33: customization forever.',
  'Memo #34: orange forever.',
  'Broadcast #35: boop received.',
  'Signal #36: blink complete.',
  'Fun fact #37: cones are friends.',
  'Day 38: still a cone.',
  'Message #39 from the void.',
  'Whisper #40: ships mods carefully.',
  'Oracle says #41: stay hydrated.',
  'Debug log #42: all orange.',
  'Secret #43: the cone knows.',
  'Tip #44: save before Build & Play.',
  'Note #45: drag me by the head.',
  'Ping #46: still watching.',
  'Chapter 47: the cone blinks.',
  'Episode 48: looking around.',
  'Quirk #49: I say anything.',
  'Rumor #50: Pro pets hit different.',
  'Spark #51: customization forever.',
  'Memo #52: orange forever.',
  'Broadcast #53: boop received.',
  'Signal #54: blink complete.',
  'Fun fact #55: cones are friends.',
  'Day 56: still a cone.',
  'Message #57 from the void.',
  'Whisper #58: ships mods carefully.',
  'Oracle says #59: stay hydrated.',
  'Debug log #60: all orange.',
  'Secret #61: the cone knows.',
  'Tip #62: save before Build & Play.',
  'Note #63: drag me by the head.',
  'Ping #64: still watching.',
  'Chapter 65: the cone blinks.',
  'Episode 66: looking around.',
  'Quirk #67: I say anything.',
  'Rumor #68: Pro pets hit different.',
  'Spark #69: customization forever.',
  'Memo #70: orange forever.',
  'Broadcast #71: boop received.',
  'Signal #72: blink complete.',
  'Fun fact #73: cones are friends.',
  'Day 74: still a cone.',
  'Message #75 from the void.',
  'Whisper #76: ships mods carefully.',
  'Oracle says #77: stay hydrated.',
  'Debug log #78: all orange.',
  'Secret #79: the cone knows.',
  'Tip #80: save before Build & Play.',
  'Note #81: drag me by the head.',
  'Ping #82: still watching.',
  'Chapter 83: the cone blinks.',
  'Episode 84: looking around.',
  'Quirk #85: I say anything.',
  'Rumor #86: Pro pets hit different.',
  'Spark #87: customization forever.',
  'Memo #88: orange forever.',
  'Broadcast #89: boop received.',
  'Signal #90: blink complete.',
  'Fun fact #91: cones are friends.',
  'Day 92: still a cone.',
  'Message #93 from the void.',
  'Whisper #94: ships mods carefully.',
  'Oracle says #95: stay hydrated.',
  'Debug log #96: all orange.',
  'Secret #97: the cone knows.',
  'Tip #98: save before Build & Play.',
  'Note #99: drag me by the head.',
  'Ping #100: still watching.',
  'Chapter 101: the cone blinks.',
  'Episode 102: looking around.',
  'Quirk #103: I say anything.',
  'Rumor #104: Pro pets hit different.',
  'Spark #105: customization forever.',
  'Memo #106: orange forever.',
  'Broadcast #107: boop received.',
  'Signal #108: blink complete.',
  'Fun fact #109: cones are friends.',
  'Day 110: still a cone.',
  'Message #111 from the void.',
  'Whisper #112: ships mods carefully.',
  'Oracle says #113: stay hydrated.',
  'Debug log #114: all orange.',
  'Secret #115: the cone knows.',
  'Tip #116: save before Build & Play.',
  'Note #117: drag me by the head.',
  'Ping #118: still watching.',
];

export function randomConeSaying(exclude?: string): string {
  if (!conePetSayings.length) return 'Boop.';
  let next = conePetSayings[Math.floor(Math.random() * conePetSayings.length)]!;
  if (exclude && conePetSayings.length > 1) {
    let guard = 0;
    while (next === exclude && guard < 8) {
      next = conePetSayings[Math.floor(Math.random() * conePetSayings.length)]!;
      guard += 1;
    }
  }
  return next;
}
